import { Resend } from 'resend';

const resend = process.env.RESEND_API_KEY
    ? new Resend(process.env.RESEND_API_KEY)
    : null;

interface SendEmailOptions {
    to: string;
    subject: string;
    html: string;
    attachments?: {
        filename: string;
        content: Buffer;
    }[];
}

/**
 * Send an email with optional PDF attachment
 */
export async function sendEmail(options: SendEmailOptions): Promise<{ success: boolean; error?: string }> {
    const isMockMode = process.env.MOCK_MODE === 'true';

    if (isMockMode) {
        console.log('[Email] Mock mode enabled, simulating email send');
        console.log('[Email] Would send to:', options.to);
        console.log('[Email] Subject:', options.subject);
        await new Promise(resolve => setTimeout(resolve, 1000));
        return { success: true };
    }

    if (!resend) {
        console.error('[Email] RESEND_API_KEY is not configured');
        return { success: false, error: 'Email service not configured' };
    }

    try {
        const { data, error } = await resend.emails.send({
            from: 'PrescriptoAI <onboarding@resend.dev>',
            to: options.to,
            subject: options.subject,
            html: options.html,
            attachments: options.attachments,
        });

        if (error) {
            console.error('[Email] Error sending email:', error);
            return { success: false, error: error.message };
        }

        console.log('[Email] Email sent successfully:', data?.id);
        return { success: true };
    } catch (error) {
        console.error('[Email] Error sending email:', error);
        return {
            success: false,
            error: error instanceof Error ? error.message : 'Failed to send email'
        };
    }
}

/**
 * Generate email HTML template for prescription notes
 */
export function generatePrescriptionEmailHTML(prescriptionId: string): string {
    return `
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Prescription Notes</title>
</head>
<body style="margin: 0; padding: 0; font-family: Arial, sans-serif; background-color: #f4f4f4;">
    <table role="presentation" style="width: 100%; border-collapse: collapse;">
        <tr>
            <td align="center" style="padding: 40px 0;">
                <table role="presentation" style="width: 600px; max-width: 90%; border-collapse: collapse; background-color: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">
                    <!-- Header -->
                    <tr>
                        <td style="background: linear-gradient(135deg, #3b82f6, #6366f1); padding: 30px; text-align: center;">
                            <h1 style="margin: 0; color: #ffffff; font-size: 24px;">💊 PrescriptoAI</h1>
                            <p style="margin: 10px 0 0; color: rgba(255, 255, 255, 0.9); font-size: 14px;">Your Medication Notes</p>
                        </td>
                    </tr>
                    
                    <!-- Content -->
                    <tr>
                        <td style="padding: 30px;">
                            <h2 style="margin: 0 0 15px; color: #1f2937; font-size: 20px;">Hello! 👋</h2>
                            <p style="margin: 0 0 20px; color: #4b5563; font-size: 15px; line-height: 1.6;">
                                Your prescription summary is attached to this email as a PDF. You can download it, print it, or save it for reference.
                            </p>
                            
                            <!-- Warning Box -->
                            <div style="background-color: #fef3c7; border-left: 4px solid #f59e0b; padding: 15px; border-radius: 0 8px 8px 0; margin: 20px 0;">
                                <p style="margin: 0; color: #92400e; font-size: 14px;">
                                    <strong>⚠️ Important:</strong> This summary is for informational purposes only. Always verify with your doctor or pharmacist before taking any medication.
                                </p>
                            </div>
                            
                            <p style="margin: 20px 0 0; color: #4b5563; font-size: 14px;">
                                Stay healthy! 🌟
                            </p>
                        </td>
                    </tr>
                    
                    <!-- Footer -->
                    <tr>
                        <td style="background-color: #f9fafb; padding: 20px 30px; text-align: center; border-top: 1px solid #e5e7eb;">
                            <p style="margin: 0; color: #9ca3af; font-size: 12px;">
                                Generated by PrescriptoAI • Your data is automatically deleted after 24 hours
                            </p>
                            <p style="margin: 8px 0 0; color: #9ca3af; font-size: 11px;">
                                Prescription ID: ${prescriptionId.slice(0, 8)}
                            </p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>
</html>
    `;
}
